---
# HEADER SECTION
 - name: This playbook will restart ur system service
   hosts: webservers
   gather_facts: True

# TASK SECTION
   tasks:
     - name: To Restart the service if its 64 bit
       service:
         name: sshd
         state: restarted
       when: ansible_architecture == "x86_64"

     - name: OR statement
       service:
         name: sshd
         state: restarted
       when: ( ansible_distribution == "Ubuntu" or ansible_architecture == "x86_64" )

     - name: AND statement
       service:
         name: sshd
         state: restarted
       when: ( ansible_distribution == "RedHat" and ansible_architecture == "x86_64" )

     - name: To make sure the file is always present
       file:
         path: /opt/file1.txt
         state: file
       when: 
         - ansible_processor_cores >= 1
         - ansible_distribution == "RedHat"

     - name: To copy a file to all remote servers
       copy:
         src: /etc/ansible/ansible.cfg
         dest: /opt/ansible.cfg
         owner: root
         group: root
         mode: 0644
       when: ansible_memtotal_mb >= 4096

     - name: To use the data of the fact as a variable
       file:
         path: /opt/{{ ansible_distribution }}
         state: touch
